- .github/pull_request_template.md
Issue: https://github.com/Alecell/octopost/issues/26
<summary>
<b>Feature</b>
</summary>
This docs update adds a pull request template to set a standard for all of the pull requests. The provided solution is based on github documentation [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository).
</details>
<details> 
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
- Adds a file `pull_request_template` 
</details>
<details> 
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> …
> chore: (docs): update github pull request template

- .czferc.js
Issue: #61 
<summary>
<b>Refactor</b>
</summary>
Remove `scope` from commitizen 
- **Cause**
Remove `scope` from commitizen, because is not actively being utilized by team members.
- **Solution**
Remove `scope` from commitizen
</details>
<summary>
</summary>
Remove scope from commitizen
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
> refactor: remove scope from commitizen #61

- .github/workflows/main.yml
- package.json
- src/components/Switch/Switch.module.scss
- src/components/TextCopy/TextCopy.module.scss
- src/components/ToggleSocialMedia/ToggleSocialMedia.module.scss
- src/pages/home/home.module.scss
Issue:  https://github.com/Alecell/octopost/issues/88
<summary>
<b>Bugfix</b>
</summary>
Our Stylelint needs to be checked on CI
- **Cause**
Missed configuration for stylelint on github action
- **Solution**
Added Stylelint command and used on Github Action.
</details>
<summary>
</summary>
- Created stylelint command
- Fixed CI indentation
- Added Stylelint command on CI
- Fix stylelint on components to previne errors
</details>
<summary>
</summary>
| Stylelint on CI |
|--------|
| ![image](https://github.com/Alecell/octopost/assets/61947632/5bc6f97d-551f-4596-98e1-f51c50601ab8)| 
</details>
<summary>
</summary>
</details>
<details …
> Add stylelint on CI

- package.json
- src/components/Switch/Switch.stories.tsx
- src/components/Switch/Switch.tsx
Issue: N/A
<summary>
<b>Feature</b>
</summary>
We had to create stories for our components, and to make by example I created this pull request creating an example of a Switch component on Ladle.
</details>
<summary>
</summary>
- Created switch stories
- Added a command on package.json to initialize Ladle
- Fixed a typo on Switch Component
</details>
<summary>
</summary>
| Switch Component |
|--------|
| ![switch](https://github.com/Alecell/octopost/assets/61947632/8a59d0e6-5b7d-4dc5-be68-22c3ab111e89) | 
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
> Add stories for Switch Component

- .github/issue_template.md
Issue:  #82 
Create a new `template issue` for open new issues on github.
</details>
<summary>
</summary>
- add a new `issue_template.md` on `.github` dir
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
> docs: add a new template for issues on github

- src/components/Preview/Preview.spec.tsx
- src/components/Preview/Preview.tsx
- src/components/Preview/Preview.types.ts
- src/components/preview/index.tsx
Issue: #59 
<summary>
<b>Refactor</b>
</summary>
refactor the preview component to follow the styleguide and add tests
</details>
<summary>
</summary>
- change the folder name to CamelCase
- refactor the component to follow the styleguide
- add tests
</details>
<summary>
</summary>
</details>
> Refactor preview

- .github/ISSUE_TEMPLATE/issue_template.md
Issue: N/A
<summary>
<b>Bugfix</b>
</summary>
The issue template needs this initial info to work properly on GitHub
- **Cause**
missed configuration
- **Solution**
added configuration provided
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
> fix: add the required info to create a new issue template

- .husky/prepare-commit-msg
- .lintstagedrc.json
- package.json
- yarn.lock
Issue: #96 
<summary>
<b>Feature</b>
</summary>
We need to implement a pre commit hook to check if the user properly used our style preferences. To avoid losing some time doing this on code review.
</details>
<summary>
</summary>
- Added lint staged lib
- Updated pre commit husky hook
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
> docs: add lint staged to check if have any issue on code before commit

- src/components/TextArea/TextArea.stories.tsx
Issue: docs #102 
create ladle storie for `text area` component
- **Cause**
renders was in App.tsx, causing conflicts
- **Solution**
use ladle to render the component for testing
</details>
<details> 
<summary>
</summary>
- add a new file `TextArea.stories.tsx`
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
> docs: add storie for text area

- src/components/ToggleSocialMedia/ToggleSocialMedia.stories.tsx
Issue:  docs #103
<summary>
<b>Feature</b>
</summary>
This issue create a new Storie with the controls to control our component props.
</details>
<summary>
</summary>
- Added storie with controls
</details>
<summary>
</summary>
| Using controls |
|--------|
| ![toggleSocial](https://github.com/Alecell/octopost/assets/61947632/6a9f7d6f-5169-4a6a-b78f-4f400b2bd7a1) | 
</details>
<summary>
</summary>
</details>
> docs: Add storie documentation to toggleSocialMediaComponent with controls

- src/components/Preview/Preview.stories.tsx
Issue: #100 
<summary>
<b>Feature</b>
</summary>
This issue create a new Storie with the controls to control our component props.
</details>
<summary>
</summary>
- Added storie with controls
</details>
<summary>
</summary>
| Using controls |
|--------|
|![2023-08-19-19-39-11](https://github.com/Alecell/octopost/assets/103784814/145869fe-d1f7-43c3-8374-369303b817ff)| 
</details>
<summary>
</summary>
</details>
> docs: add preview component to ladle documentation

- src/components/TextArea/TextArea.spec.tsx
Issue: test #93 
add test using jest for TextArea component
</details>
<summary>
</summary>
- add `TextArea.spec.tsx` 
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
> test: add test for textarea component #93

- src/components/CharacterLimit/CharacterLimit.stories.tsx
Closes #98 
<summary>
<b>Feature</b>
</summary>
Create a story for a component that was created before Ladle was implemented.
</details>
<details> 
<summary>
</summary>
- Create stories for character limit component
</details>
<summary>
</summary>
| Component on ladle |
|--------|
| ![image](https://github.com/Alecell/octopost/assets/61947632/8f8ca083-db08-4f92-a856-d9a5f0329784) | 
</details>
<summary>
</summary>
</details>
> feat: create character limit stories

- .stylelintrc
- .vscode/extensions.json
- src/components/InputSearch/IInputProps.types.ts
- src/components/InputSearch/InputSearch.module.scss
- src/components/InputSearch/InputSearch.spec.tsx
- src/components/InputSearch/InputSearch.stories.tsx
- src/components/InputSearch/InputSearch.tsx
- src/components/InputSearch/InputSearch.types.ts
- src/components/SearchClue/SearchClue.module.scss
- src/components/SearchClue/SearchClue.spec.tsx
- src/components/SearchClue/SearchClue.tsx
- src/components/SearchClue/SearchClue.types.ts
- src/pages/home/components/Sidebar/Sidebar.tsx
Closes 
<summary>
<b>Feature</b>
</summary>
Merge two components "SearchClue" and "inputSearch" on Sidebar.
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
> feat: Merge and fix the SearchClue and inputSearch on sidebar

- .github/dependabot.yml
- .github/workflows/main.yml
- README.md
- package.json
- pnpm-lock.yaml
Closes #238 
<summary>
<b>Feature</b>
</summary>
Foi trocado o yarn pelo pnpm, também foi excluido algumas dependencias depreciadas.
</details>
<summary>
</summary>
</details>
<summary>
</summary>
- Projeto Rodando com pnpm
</details>
> Change yarn to pnpm and remove deprecated dependencies

- src/components/AccordionTab/AccordionTab.module.scss
- src/components/CharacterLimitMainText/components/CharacterLimit.tsx
- src/components/MainComposer/MainComposer.module.scss
Closes
<summary>
<b>Feature</b>
</summary>
I adjusted the AccordionTab TextArea to fill the entire space of the component.
I also added the maximum allowed value to the remaining character count indicator, analogous to the prototype, and change the size of AccordionTab circle.
Issue - #358
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
</details>
> AccordionTab TextArea Adjustment

- src/components/Button/Button.stories.tsx
Closes #442 
<summary>
<b>Bugfix</b>
</summary>
Reajustando os stories do componente de button.
- **Cause**
No PR #412 o arquivo button.stories.tsx foi alterado para a sua versão antiga que já tinha sido arrumado no PR #436. Agora é necessário ajustar para a sua atualização correta.
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
Antes:
Depois:
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
> Reajuste dos stories do Button

- src/components/Modal/Modal.module.scss
- src/components/Modal/Modal.stories.tsx
- src/components/Modal/Modal.tsx
Closes #428 
<summary>
<b>Feature</b>
</summary>
Ajuste do modal para segundo o figma, e alguns ajustes de componentes internos como icon.
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
Antes:
<br/>
Depois:
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
> Issue 428 - Ajuste do Modal segundo o design do figma

- src/components/Checkbox/Checkbox.stories.tsx
- src/components/Checkbox/Checkbox.tsx
Closes #369 
<summary>
<b>Feature</b>
</summary>
Tornando o componente que era apenas controlado para ser também descontrolado caso o componente pai não use a props `checked`.
</details>
<summary>
</summary>
[checkbox.webm](https://github.com/devhatt/octopost/assets/90076846/d17fe54f-1bcb-4f81-a6ee-022c2a049b06)
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
> Issue 369 - checkbox possa ser descontrolado e controlado

- src/components/CharacterLimitMainText/CharacterLimitMainText.spec.tsx
- src/components/CharacterLimitMainText/components/CharacterLimit.tsx
Closes #506  
<summary>
<b>Feature</b>
</summary>
Essa task tinha como objetivo em alterar o test que antes era com `className` e agora o test passou a ser com `getAllByText`. Nesse PR fiz somente a alteração do test. 
</details>
<summary>
</summary>
<summary>
</summary>
</details>
</details>
> refactor the test for the use of getAllByText

- src/components/CharacterLimitMainText/CharacterLimit.module.scss
- src/components/MainComposer/components/ComposerEditor/ComposerEditor.tsx
- src/components/MainComposer/components/ComposerEditor/ComposerEditor.types.ts
- src/components/MainComposer/components/MainComposerBase/MainComposerBase.tsx
- src/components/MainComposer/components/MainComposerBase/MainComposerBase.type.ts
- src/components/Tabber/Tabber.tsx
Closes #557 
<summary>
<b>Feature</b>
</summary>
Character limit exibindo o limite de cada postmode de cada rede social separadamente ao invés do total como é feito no MainComposer.
</details>
<summary>
[CharacterLimit.webm](https://github.com/devhatt/octopost/assets/90076846/eae188c3-b90d-4aa3-aad5-1b9ce84d5eee)
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
> Character limit no MainComposer do Tabber

- src/components/FeedbackError/FeedbackError.tsx
- src/components/Icon/data.ts
- src/components/Icon/icons/TriangleLeftArrow.svg
- src/pages/home/components/ActionBar/ActionBar.tsx
- src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.tsx
Closes #548 
<summary>
<b>Feature</b>
</summary>
A tarefa consiste em ajustar a seta do socialAccordion para manter a consistência do layout, pois, antes, tínhamos dois tipos de setas diferentes, conforme retrata a imagem abaixo.
Eu também fiz uma mudança no nome da "seta" para baixo. No projeto, temos ícones que são, de fato, setas, e temos triângulos que lembram setas, porém são triângulos e, em algum momento, poderia acabar havendo uma confusão do ponto de vista semântico. Portanto, em vez de chamar dropDownArrow, agora chama-se TriangleDropArrow (dando a entender que é uma seta para baixo, mas em formato de triângulo).
<summary>
</summary>
Layout:
Como esta:
Como estava:
<summary>
</summary>
</details>
> chore: add correct icon & adjust name

- eslint.config.mjs
- package.json
- setup.mjs
Closes #564 
<summary>
<b>Feature</b>
</summary>
Cria um arquivo .env com base no arquivo que tem no repositorio de envs, facilitando assim a iniciação do projeto e padronizando as envs base.
</details>
<summary>
</summary>
</details>
> Script to create .env

- src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.spec.tsx
Closes #509 
<summary>
<b>Feature</b>
</summary>
Correção dos testes do SocialAccordion
</details>
<summary>
<b>Visual evidences :framed_picture: </b>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
1. Adicionado o mock da store de account para que os métodos addAccount e removeAccount sejam testados.
2. Adicionada variáveis para melhor leitura
3. Simplificado alguns testes
4. Adicionado testes de adicionar e remover conta ativadas no tabber
</details>
> fix: socialaccordion test

- src/components/AccordionTab/AccordionTab.module.scss
- src/components/AccordionTab/AccordionTab.tsx
- src/components/Icon/data.ts
- src/components/Icon/icons/circle.svg
Closes #547 
<summary>
<b>Feature</b>
</summary>
Pequenos ajustes no componente AccordionTab para manter a consistência do layout, seguindo o Figma.</details>
<summary>
</summary>
Descricao da issue:
Como Ficou:
Como estava:
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
</details>
> refactor: adjust the accordio tab header

- src/components/MainComposer/components/InputMediaGroup/InputMediaGroup.module.scss
- src/components/MainComposer/components/InputMediaGroup/components/InputMedia/InputMedia.module.scss
Closes #542 
<summary>
<b>Feature</b>
</summary>
Antes de tudo, é importante destacar que, segundo o Ale, não há necessidade de seguir à risca a consistência do layout, pois, futuramente, esse componente passará por alterações. Foram realizadas modificações para que o campo de entrada de mídia tenha um tamanho padrão e consistente. Além disso, o "X", que é responsável por remover uma mídia já adicionada, foi ajustado, já que anteriormente ele apresentava um formato oval em vez de circular.
</details>
<summary>
</summary>
Estava:
https://github.com/user-attachments/assets/82cfce4b-455e-43b2-a774-9e371898297f
Ficou/esta:
https://github.com/user-attachments/assets/fd200a32-6aa1-47e5-bed2-e2ff53bd239c
</details>
<details …
> refactor: adjust input media aesthetics details

- src/components/MainComposer/components/ComposerEditor/ComposerEditor.module.scss
- src/components/Preview/Preview.module.scss
- src/components/Tabber/PostModes/PostModes.module.scss
Closes #614 
<summary>
<b>Feature</b>
</summary>
Minha task consistia, única e exclusivamente, em fazer o reajuste da responsividade do tabber.
Conforme mostra a image abaixo, ele nao se ajustava:
</details>
<summary>
</summary>
Como estava:
https://github.com/user-attachments/assets/ef2a3469-939c-451a-b6c6-bc0836bfb1ba
Como ficou:
https://github.com/user-attachments/assets/10c81673-5f1b-4b81-92d8-7830e659a6c4
](url)
</details>
<summary>
</summary>
</details>
> refactor: readjust tabber responsive

- mock-api.json
- src/components/AccountCard/AccountCard.tsx
- src/pages/home/components/Sidebar/Sidebar.components.tsx
- src/pages/home/components/Sidebar/Sidebar.spec.tsx
- src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.spec.tsx
- src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.stories.tsx
- src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.tsx
- src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.type.ts
- src/services/api/accounts/accounts.ts
- src/services/api/accounts/accounts.types.ts
- src/stores/__mocks__/useSocialMediaStore.mock.ts
- src/stores/useSocialMediaStore/useSocialMediaStore.spec.ts
- src/stores/useSocialMediaStore/useSocialMediaStore.ts
- src/stores/useSocialMediaStore/useSocialMediaStore.types.ts
Closes #470 
<summary>
<b>Feature</b>
</summary>
Adicionar funcionalidade de favoritar as contas de redes sociais
<summary>
<b>Visual evidences:
</b>
</summary>
</details>
<summary>
</summary>
</details>
> issue-470 - favoritar contas

- src/pages/home/components/ActionBar/ActionBar.module.scss
- src/pages/home/components/ActionBar/ActionBar.tsx
Closes #610 
<summary>
<b>Feature</b>
</summary>
Ajusta o botão da action bar para ficar disabled a não ser que haja alguma conta selecionada
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
> fix: only allow action bar button when at least one account is selected
