devhatt/octopost

- STYLEGUIDE.md
<details> 
<summary>
</summary>
Create style guide documentation file
</details>
> docs: create style guide documentation file

- CODE_OF_CONDUCT.md
Issue: #54 
<summary>
<b>Feature</b>
</summary>
Codigo de conduta
</details>
<details> 
<summary>
</summary>
CODE_OF_CONDUCT.md 
</details>
<summary>
</summary>
</details>
> docs(CODE_OF_CONDUCT.md): codigo de conduta

- STYLEGUIDE.md
Issue: #73 
<summary>
<b>docs</b>
</summary>
add rules to styleguide
</details>
<details> 
<summary>
</summary>
update the STYLEGUIDE.md file
</details>
<summary>
</summary>
</details>
> docs: add some rules on styleguide

- CONTRIBUTING.md
Issue: #53 
<details> 
<summary>
</summary>
CONTRIBUTING.md
</details>
<summary>
</summary>
</details>
> docs(CONTRIBUTING.md): Diretrizes de contribuição

- package.json
- src/components/Testinho/Testinho.stories.tsx
- src/components/Testinho/Testinho.tsx
- yarn.lock
Issue: feat #63
<summary>
<b>Feature</b>
</summary>
</details>
This Pull Request implement the UI Component Manager `landle` for develop and test components and add a test button to the `Testinho.tsx` file to facilitate testing and integration with Landle.
- **Cause**
Problems with component tests when they were done directly in the file `App.tsx`
- **Solution**
We'll use `landle` to enhance tests of the components of our project.
</details>
<summary>
- add `landle` dependencies on `package.json`
- add a `test button` on `Testinho.tsx`
- add new file `Testinho.stories.tsx` for tests on `landle`
</summary>
</details>
<summary>
</summary>
</details>
<details open> …
> feat: add landle and test button #63

- src/components/Switch/Switch.spec.tsx
Issue: #67 
<summary>
<b>Test</b>
</summary>
add tests for switch component 
</details>
<details> 
<summary>
</summary>
add test file on switch component
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
</details>
> add unit tests for switch component

- README.md
Issue: #80
<summary>
<b>Documentation</b>
</summary>
Added github badges to the Readme
</details>
<details> 
<summary>
</summary>
Added links and images to the Readme file
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
> docs: Added badges and links to the readme

- .github/pull_request_template.md
Closes #112 
<summary>
<b>Chore</b>
</summary>
change the pr template to close the issue automatically
</details>
<details> 
<summary>
</summary>
change pull_request_template.md
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
> chore: change pr template

- src/components/InputImage/InputImage.module.scss
- src/components/InputImage/InputImage.spec.tsx
- src/components/InputImage/InputImage.tsx
> Input image

- src/pages/home/components/Header/Header.module.scss
- src/pages/home/components/Header/Header.stories.tsx
- src/pages/home/components/Header/Header.tsx
- src/pages/home/components/Sidebar/Sidebar.module.scss
- src/pages/home/components/Sidebar/Sidebar.stories.tsx
- src/pages/home/components/Sidebar/Sidebar.tsx
- src/pages/home/components/Sidebar/images/dot.svg
- src/pages/home/home.module.scss
- src/pages/home/home.tsx
Issue: #114 
<summary>
<b>Feature</b>
</summary>
- Create sidebar and header section.
</details>
<summary>
<b>Bugfix</b>
</summary>
Adjust main container borders and paddings
- **Cause**
The borders and paddings was just for testing, and were conflicting with our new components
- **Solution**
Remove borders and adjust paddings
</details>
<summary>
</summary>
- [Add new `header` section](https://github.com/Alecell/octopost/pull/136/commits/0b249464b3c842f7b270053f9472e2325eb1ac0f)
- [Add new `sidebar` section](https://github.com/Alecell/octopost/pull/136/commits/41fc66c5dd92b5ed3be8edcf81a8bddab4972021)
- [Adjust sizes of `home` containers](https://github.com/Alecell/octopost/pull/136/commits/10303c7106b283d0 …
> Feat side bar/#114

- public/index.html
- src/styles/base.scss
- src/styles/global.scss
Closes 
<summary>
<b>Feature</b>
</summary>
Create the theme configuration
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
Created a global.css on global style folder.
</details>
> feat: create the theme configuration

- src/components/CharacterLimit/CharacterLimit.module.scss
- src/components/ComposerEditor/ComposerEditor.module.scss
- src/components/TextArea/TextArea.module.scss
- src/components/TextArea/TextArea.tsx
- src/pages/home/components/Sidebar/Sidebar.module.scss
- src/pages/home/home.module.scss
- src/pages/home/home.tsx
- src/styles/base.scss
<summary>
<b>Feature #131 </b>
</summary>
</details>
add style for the main content and text area and edited the variables from sidebar
</details>
<summary>
</summary>
- [edit `sidebar.modules.scss`](https://github.com/Alecell/octopost/commit/27510b113fe543f257573fcd60823f2f1998660c)
- [edit main content and textarea style](https://github.com/Alecell/octopost/commit/b991fee2cde9b9d539e5b73cc54ef83535e5c538)
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
> Feat/main text#131

- src/pages/home/components/Sidebar/Sidebar.module.scss
- src/pages/home/components/Sidebar/Sidebar.tsx
Closes #32  
<summary>
</summary>
- add `scrollbar` to the sidebar container 
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
> feat: add scrollbar for sidebar container

- src/components/CharacterLimit/CharacterLimit.module.scss
- src/components/ComposerEditor/ComposerEditor.module.scss
- src/components/Switch/Switch.module.scss
- src/components/TextArea/TextArea.module.scss
- src/components/ToggleSocialMedia/ToggleSocialMedia.module.scss
- src/components/ToggleSocialMedia/components/UserImage/UserImage.module.scss
- src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.module.scss
- src/styles/base.scss
> fix: new fix @use sass

- CONTRIBUTING.md
- FLOWISSUE.md
Add issues flow
A description was made of how beginners can catch their  issues.
> feat: Add flowIssues

- src/components/MainComposer/MainComposer.module.scss
- src/components/MainComposer/MainComposer.stories.tsx
- src/components/MainComposer/MainComposer.tsx
- src/components/TextArea/TextArea.tsx
Feat #130
- Create new Main Composer text area
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
Tests weren`t created
</details>
> feat: Add Main Composer Container

- .github/workflows/playwright.yml
- src/components/MediaInputs/MediaInput.spec.ct.tsx
Closes 
#174 
#89 
<summary>
<b>Feature</b>
</summary>
Fix mediaInput tests and add component tests for playwright
</details>
<summary>
</summary>
</details>
> feat: fix mediaInput test

- package.json
- src/components/MainComposer/MainComposer.tsx
- src/i18n/index.tsx
- src/i18n/locales/en/en-us.json
- src/i18n/locales/pt/pt-br.json
- src/pages/home/home.tsx
- yarn.lock
BREAKING CHANGE: It replace all inner aplication textication texts
Closes #120 
- Add internationalization
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
Tests weren`t created
</details>
> feat: Add internationalization

- src/components/ComponentPreview/PreviewContainer.module.scss
- src/components/ComponentPreview/PreviewContainer.spec.tsx
- src/components/ComponentPreview/PreviewContainer.stories.tsx
- src/components/ComponentPreview/PreviewContainer.tsx
- src/components/ComponentPreview/PreviewContainer.types.ts
- src/components/Tabber/Tabber.module.scss
- src/components/Tabber/Tabber.tsx
- src/pages/home/home.module.scss
- src/pages/home/home.tsx
Closes [Componente de preview#178](https://github.com/Alecell/octopost/issues/178)
<summary>
<b>Feature</b>
</summary>
- Foi criado um componente container para o preview
</details>
<details> 
<summary>
</summary>
-  Criado Pasta `Componente Preview`
-  Criado `PreviewContainer.stories.tsx`
- Usado para adicionar o componente no StoryBook
-  Criado `PreviewContainer.module.scss`
- Usado para estilizar o componente 
-  Criado `PreviewContainer.types.ts`
- Usado para adicionar a tipagem do componente
-  Criado `PreviewContainer.tsx`
- Componente do container 
-  Criado `PreviewContainer.spec.tsx`
- Teste Unitário para saber se o componente container está renderizando corretamente o conteudo
-   `PreviewContainer` inserido na `Home`
- O componente foi …
> Componente de preview

- README.md
docs #194
Closes 
<summary>
<b>Feature</b>
</summary>
- atualizei o arquivo readme para colocar os cargos, e o que cada um significa, como conseguí-los;
-  também coloquei mais uma etapa no processo de como iniciar o projeto, adicionando as extensões;
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
> docs: update readme file with roles from discord

- jest.config.js
- package.json
- src/components/CharacterLimitMainText/CharacterLimitMainText.tsx
- src/components/ComposerEditor/ComposerEditor.tsx
- src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.tsx
Closes #193 
<summary>
<b>Feature</b>
</summary>
- Testes corrigidos e passando normalmente
</details>
<summary>
<b>Bugfix</b>
</summary>
Testes acusavam diversos erros
- **Cause**
Erro no import alias e não inserção de uma key no component
- **Solution**
Remoção do alias e inserção da key no component
</details>
<details> 
<summary>
</summary>
- Corrigido erro das configurações do jest
- Remoção do path alias
- Inserção de key em component 
</details>
<summary>
</summary>
</details>
<summary>
</summary>
O create react app, estava tornando bem dificil/impossivel, trabalhar com alias, devido a isso foi necessária a remoção do mesmo, quando o projeto for …
> Corrigir warnings do jest

- .github/workflows/createBranchAssign.yml
Closes 
<summary>
<b>Feature</b>
</summary>
N/A
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
> add permissions contents write

- .changeset/config.json
Closes :x: 
<summary>
<b>Feature</b>
</summary>
Change base branch
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
> Change base branch of changeset file

- .changeset/config.json
- .github/workflows/release.yml
- package.json
> Atualiza changeset para gerar releases em projetos privados 

- .changeset/cool-pans-appear.md
- .changeset/hip-zoos-matter.md
- .changeset/lazy-apples-smoke.md
- .changeset/pre.json
- .changeset/silly-cameras-glow.md
- .changeset/slow-vans-think.md
- .github/workflows/code-style.yml
- .github/workflows/e2e.yml
> Alvarogfn patch 1

- .eslintrc.cjs
- src/App.tsx
- src/components/Button/Button.stories.tsx
- src/components/FeedbackError/FeedbackError.stories.tsx
- src/components/FeedbackError/FeedbackError.tsx
- src/components/Head/Head.tsx
- src/components/Tabber/stores/useSocialNetworkStore.tsx
- src/components/Testinho/Testinho.tsx
- src/pages/home/home.tsx
- tsconfig.json
- vite.config.ts
Closes #316
<summary>
<b>Feature</b>
</summary>
Raiz do projeto definida como base path, imports na src optimizados com ajuda do @alvarogfn, pasta electron adicionada ao path alias
</details>
<summary>
</summary>
Principais alterações feitas na `tsconfig.json`
Todas outras alterações feitas fora do tsconfig foram correções de import/ correções de eslint
</details>
<summary>
- Antes
- Depois
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
> feat: path alias to electron and optimize src path

- .github/CODEOWNERS
Closes ❌ 
Fixes a small issue on codeowners file
> change codeowners file to wildcard all files

- .eslintrc.cjs
- src/components/Checkbox/Checkbox.module.scss
- src/components/Checkbox/Checkbox.spec.tsx
- src/components/Checkbox/Checkbox.stories.tsx
- src/components/Checkbox/Checkbox.tsx
- src/components/Checkbox/Checkbox.types.ts
- src/components/FirstComment/FirstComment.tsx
- vitest.config.ts
closes #416 
Refatorar o componente de Checkbox corrigindo os erros de eslint e arrumando os padrões
> refactor: checkbox

- src/components/Switch/Switch.module.scss
- src/components/Switch/Switch.spec.tsx
- src/components/Switch/Switch.stories.tsx
- src/components/Switch/Switch.tsx
- src/components/Switch/Switch.types.ts
- src/components/ToggleSocialMedia/ToggleSocialMedia.tsx
- vitest.config.ts
Refatora o componente de Switch arrumando os erros de eslint e colocando em um padrão
Closes #417
> refactor: switch

- src/components/Button/Button.stories.tsx
- src/components/ComposerEditor/ComposerEditor.stories.tsx
- src/components/FeedbackError/FeedbackError.module.scss
- src/components/FeedbackError/FeedbackError.tsx
- src/components/Tabber/Tabber.tsx
- src/components/Tabber/Tabber.types.ts
Closes #434 
<summary>
<b>Bugfix</b>
</summary>
Componentes com problema quebrando no ladle.
- **Cause**
Houveram mudanças em alguns componentes, como o Icon, que afetaram outros componentes e estes estavam quebrando quando testados no ladle do projeto.
- **Solution**
Verifiquei os seguintes componentes e corrigi o suficiente para que sejam executados no ladle e visualizados:
* Button
* Compose Editor
* Feedback error
* Tabber
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<summary>
</summary>
É importante destacar que foi realizado …
> Issue 434 - Corrigir problemas com componentes no ladle

- src/components/Button/Button.stories.tsx
Closes #442 
<summary>
<b>Bugfix</b>
</summary>
Reajustando os stories do componente de button.
IMPORTANTE: O PR mergeado anteriormente foi mergeado na branch issue-442 em vez da master, por isso precisei fazer esse novo PR.
- **Cause**
No PR #412 o arquivo button.stories.tsx foi alterado para a sua versão antiga que já tinha sido arrumado no PR #436. Agora é necessário ajustar para a sua atualização correta.
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
Antes:
Depois:
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
> fix: readjusing the stories

- package.json
- pnpm-lock.yaml
- src/components/FeedbackError/FeedbackError.data.ts
- src/components/FeedbackError/FeedbackError.module.scss
- src/components/FeedbackError/FeedbackError.spec.tsx
- src/components/FeedbackError/FeedbackError.stories.tsx
- src/components/FeedbackError/FeedbackError.tsx
- src/components/FeedbackError/FeedbackError.type.ts
- src/components/Icon/data.ts
- src/components/Icon/icons/drop-down.svg
- src/stores/useError/useError.spec.ts
- src/stores/useError/useError.ts
- src/stores/useError/useError.types.ts
Closes #374 
<summary>
<b>Feature</b>
</summary>
Foram realizados ajustes Estilísticos no Componente para ficar em conformidade com o novo Layoput. A primeira imagem representa o layout do figma e o que está em baixo ( outra imagem e vídeo ) o resultado.  
Para isso foram adicionados novos códigos e, também, estilizações. Foi preciso adicionar o novo icone da nossa lib de icones ("Alert" ) e tive que adiconar o icone que nomei como "DropDownArrow"  que representa a setinha com para baixo.
</details>
<summary>
</summary>
https://github.com/devhatt/octopost/assets/30197026/b9619f6f-192d-4e57-858a-bfceeca7a866
</details>
<summary>
</summary>
</details>
<details> 
<summary>
<b>Additional …
> refactor: add new style to FeedBackError & update the icon

- package.json
- pnpm-lock.yaml
- src/components/InputSearch/InputSearch.types.ts
- src/pages/home/components/Sidebar/Sidebar.module.scss
- src/pages/home/components/Sidebar/Sidebar.spec.tsx
- src/pages/home/components/Sidebar/Sidebar.tsx
- src/setupTests.ts
Closes #465 
<summary>
<b>Feature</b>
</summary>
</details>
Adicionada o comportamento de filtragem no input search do sidebar
<summary>
</summary>
</details>
<summary>
</summary>
</details>
> Issue 465 - Filtro do inputsearch do sidebar

- docs/CODEREVIEW.md
Um passo a passo de revisão de códigos no octopost
> feat: codereview.md

- src/components/MainComposer/components/ComposerEditor/ComposerEditor.tsx
- src/components/Tabber/PostModes/PostModes.tsx
- src/components/Tabber/PostModes/PostModes.types.ts
- src/components/Tabber/Tabber.tsx
- src/stores/useAccountStore.ts
- src/stores/useSocialMediaStore/useSocialMediaStore.ts
Closes #529 
<summary>
<b>Feature</b>
</summary>
Adcionado sincronização do conteúdo principal com as abas selecionadas pelo menu lateral, também propagado para cada tipo de postagem pra cada conta.
</details>
<summary>
[MainContent-sync.webm](https://github.com/devhatt/octopost/assets/90076846/290fbf16-eacd-477c-a951-a78eb0b9fddb)
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
> Sincronização de conteúdo principal com conteúdo de abas

- src/components/Icon/data.ts
- src/components/Icon/icons/arrow-right.svg
- src/components/InputSearch/InputSearch.module.scss
- src/components/Preview/Preview.module.scss
- src/components/Tabber/Tabber.module.scss
- src/pages/home/components/ActionBar/ActionBar.module.scss
- src/pages/home/components/ActionBar/ActionBar.tsx
- src/pages/home/components/Header/Header.module.scss
- src/pages/home/components/Header/Header.tsx
- src/pages/home/components/Sidebar/Sidebar.module.scss
- src/pages/home/components/Sidebar/Sidebar.spec.tsx
- src/pages/home/components/Sidebar/Sidebar.tsx
- src/pages/home/home.module.scss
- src/pages/home/home.tsx
Closes #533 
<summary>
<b>Feature</b>
</summary>
A task consiste em ajustar a tela inicial do layout princiapal, como a disposicao dos componentes fica na versao mobile. Isso envolve ocultar os módulos que não são necessários na versão móvel e criar a estrutura básica da página para facilitar a adição dos demais componentes conforme necessário. Como se poder ver,  nas esta igual, pois falta o desenvolvimento do layout.
<summary>
</summary>
Layout:
Minhas mudancas:
<summary>
</summary>
</details>
> Mobile home structure/#533

- .github/CODEOWNERS
Closes
<summary>
<b>Feature</b>
</summary>
N/A
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
> fix: change code owners

- src/components/Tabber/Tabs/Tabs.module.scss
- src/components/Tabber/Tabs/Tabs.tsx
Closes #618 
<summary>
<b>Feature</b>
</summary>
Adiciona ícones nas tabs
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
> feat: show social media icon on tab
